book/urls.py
from django.urls.conf import path
from . import views

app_name='book'
urlpatterns=[
    path('',views.home,name='home'),
    path('book/<id>',views.review,name='review'),
    path('hemant/<id>',views.hemant,name='hemant')

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
]+ static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title= models.CharField(max_length=100)
    author=models.CharField(max_length=50)
    langauge=models.CharField(max_length=100)
    edition=models.TextField(max_length=50)
    description=models.TextField()
    image=models.ImageField(upload_to='book/images/')


    def __str__(self):
        return self.title
        
class Review(models.Model):
    book=models.ForeignKey( Book, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    ratings=models.IntegerField()
    review=models.TextField()

    def __str__(self):
        return f'{self.book},{self.name}'

    

book/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import Book, Review
from django.urls import reverse
# Create your views here.
def home(request):
    data = Book.objects.all()
    return render(request,'book/index.html',{"books":data})

def review(request,id):
    book=Book.objects.get(id=id)
    review=Review.objects.filter(book=book)
    return render(request,'book/review.html',{"book":book, "reviews":review})

def hemant(request,id):
    review_name=request.POST.get('reviewsname')
    review_ratings=request.POST.get('reviewsratings')
    review_body=request.POST.get('reviewbody')
    book=Book.objects.get(id=id)
    review_obj=Review(book=book,name=review_name, ratings= review_ratings,review=review_body)
    review_obj.save()
    return HttpResponseRedirect(reverse('book:review', args=(id)) )

book/templates/book/index.html
<h1>hello leader</h1>

{% for book in books %}
<div>
  <a href="{% url 'book:review' book.id %}">
    <img src="{{book.image.url}}" alt="{{book.title}}" width="300px" />
    <h2>{{book.title}}</h2>
    <h3>{{book.author}}</h3>
    <p>{{book.description}}</p>
  </a>
</div>

{% endfor %}

book/templates/book/review.html
<h1>hello this is the book :{{book.title}}</h1>
<h2>this book is written by :{{book.author}}</h2>
<h3>{{book.descriptions}}</h3>
<img src="{{book.image.url}}" width="500px" />

<div>
  {% for rev in reviews %}
  <div>
    <button>
      <h4>{{rev.name}}</h4>
      <p>{{rev.ratings}}</p>
      <p>{{rev.review}}</p>
    </button>
  </div>
  {% endfor %}
</div>

<br /><br /><br />

<form method="post" action="{% url 'book:hemant' book.id %}" role="form">
  {% csrf_token %} your name:
  <input type="text" name="reviewsname" /><br />
  ratings:<input type="number" name="reviewsratings" /><br />
  review:<input type="text" name="reviewbody" />
  <br />
  <button>submit</button>
</form>